### ISSUE TITLE
cVim doesn't work in Atlassian Confluence

### ISSUE THREAD

**Issue by kovetskiy** [1995eaton/chromium-vim#174]
Example: https://confluence.atlassian.com/display/APPLINKS020/Application+Links+User+Guide
My config: https://gist.github.com/kovetskiy/07e5cebdd6f422e81cfa

**Comment by perpen** [comment]
That would be great.
Same issue on quite a few non-Confluence sites, e.g. http://fishshell.com/docs/current/index.html

**Comment by hiberabyss** [comment]
I meet the same problem. Since our company use Atlassian Confluence as internal wiki, it will bring quite convenience if adding scrolling support for it. Thanks :)

**Comment by 1995eaton** [comment]
Should be fixed now. Let me know if there's any problems with the patch and I'll reopen.

**Comment by hiberabyss** [comment]
Thanks for your so quick response!  I download the latest version (f56ea74), load it in developer mode,  disable the cvim installed from webstore, but the scroll function still doesn't work in Atlassian Confluence. I'm not sure whether I have missed some necessary steps. Thanks :)

**Comment by s-kostyaev** [comment]
Works for me with master revision. Is it possible to focus on element without mouse click?

**Comment by s-kramer** [comment]
In the latest master 0503d123b4 the scrolling still isn't working properly in Atlassian Confluence for me.
